dynamiclogin.controller.loadIframe:
    path: /loadiframe/{lgnRoot}
    defaults:
        _controller: Hhcom\ContaoDynamicLogin\Controller\AjaxController::loadIframe
        _scope: frontend
        _token_check: false
        
dynamiclogin.controller.loadIframelocale:
    path: /{_locale}/loadiframe/{lgnRoot}
    defaults:
        _controller: Hhcom\ContaoDynamicLogin\Controller\AjaxController::loadIframe
        _scope: frontend
        _token_check: false